// Business operations. Each takes a mutable draft of the DB (see store.mutate) so related records change together.
import type { Alteration, Charge, DB, ID, Lead, Order, Payment, PaymentMethod, Product, SmsLog } from './types'
import { groupByOrder, orderMoney, restingStatus } from './domain'
import { nowIso, todayStr } from '../lib/date'
import { uid } from '../lib/storage'

const kindOf = (d: DB, p: Product) => d.productTypes.find((t) => t.id === p.typeId)?.kind ?? 'dress'

function paymentsOf(d: DB, orderId: ID) {
  return groupByOrder(d.payments).get(orderId) ?? []
}

/** Releases or re-derives a dress's status once nothing specific holds it. */
function settle(d: DB, productId: ID) {
  const p = d.products.find((x) => x.id === productId)
  if (!p || kindOf(d, p) === 'accessory') return
  if (p.status === 'sold' || p.status === 'cleaning' || p.status === 'alteration') return
  p.status = restingStatus(d, productId)
}

/** `id` is generated by the caller so it can navigate to the new order afterwards. */
export function createOrder(d: DB, id: ID, draft: Omit<Order, 'id' | 'number' | 'createdAt'>, firstPayment?: { amount: number; method: PaymentMethod }): Order {
  const order: Order = { ...draft, id, number: `${d.settings.orderPrefix || 'OR'}-${d.orderSeq}`, createdAt: nowIso() }
  d.orderSeq += 1
  d.orders.push(order)
  for (const item of order.items) {
    const p = d.products.find((x) => x.id === item.productId)
    if (!p) continue
    if (kindOf(d, p) === 'accessory') {
      if (order.type === 'sale') p.quantity = Math.max(0, p.quantity - item.qty)
    } else if (p.status === 'available') {
      p.status = 'reserved'
    }
  }
  if (firstPayment && firstPayment.amount > 0) {
    addPayment(d, { orderId: order.id, branchId: order.branchId, clientId: order.clientId, amount: firstPayment.amount, kind: 'advance', method: firstPayment.method, staffId: order.staffId })
  }
  return order
}

export function addPayment(d: DB, p: Omit<Payment, 'id' | 'date'> & { date?: string }): Payment {
  const payment: Payment = { ...p, id: uid(), date: p.date ?? nowIso() }
  d.payments.unshift(payment)
  if (payment.orderId) closeIfSettled(d, payment.orderId)
  return payment
}

/** A returned rental with nothing left to pay is finished. */
function closeIfSettled(d: DB, orderId: ID) {
  const o = d.orders.find((x) => x.id === orderId)
  if (!o || o.status !== 'returned') return
  if (orderMoney(o, paymentsOf(d, orderId)).balance <= 0) o.status = 'completed'
}

export function handOver(d: DB, orderId: ID, opts: { security?: { amount: number; method: PaymentMethod } }) {
  const o = d.orders.find((x) => x.id === orderId)
  if (!o) return
  o.pickedUpAt = nowIso()
  o.status = o.type === 'sale' ? 'completed' : 'picked_up'
  if (opts.security && opts.security.amount > 0) {
    addPayment(d, { orderId, branchId: o.branchId, clientId: o.clientId, amount: opts.security.amount, kind: 'security', method: opts.security.method, staffId: o.staffId })
  }
  for (const item of o.items) {
    const p = d.products.find((x) => x.id === item.productId)
    if (!p || kindOf(d, p) === 'accessory') continue
    p.status = o.type === 'sale' ? 'sold' : 'rented'
    if (o.type === 'sale') p.quantity = 0
  }
  for (const a of d.alterations) if (a.orderId === orderId && a.status !== 'delivered') a.status = 'delivered'
}

export interface ReturnInput {
  lateFee: number
  damage: number
  damageNotes?: string
  refund: number
  method: PaymentMethod
  productStatus: Product['status']
}

export function acceptReturn(d: DB, orderId: ID, input: ReturnInput) {
  const o = d.orders.find((x) => x.id === orderId)
  if (!o) return
  const today = todayStr()
  const held = orderMoney(o, paymentsOf(d, orderId)).securityHeld
  const charge = (kind: Charge['kind'], amount: number, note?: string) => {
    if (amount > 0) o.charges.push({ id: uid(), kind, amount, note, date: today })
  }
  charge('late_fee', input.lateFee)
  charge('damage', input.damage, input.damageNotes)
  if (input.damageNotes) o.damageNotes = input.damageNotes

  // Fees are first kept out of the deposit; whatever the deposit can't cover stays on the balance.
  let fromDeposit = Math.min(held, input.lateFee + input.damage)
  const keep = (amount: number) => {
    const use = Math.min(fromDeposit, amount)
    if (use > 0) addPayment(d, { orderId, branchId: o.branchId, clientId: o.clientId, amount: use, kind: 'fee', method: input.method, fromDeposit: true, staffId: o.staffId })
    fromDeposit -= use
  }
  keep(input.lateFee)
  keep(input.damage)
  if (input.refund > 0) {
    addPayment(d, { orderId, branchId: o.branchId, clientId: o.clientId, amount: input.refund, kind: 'security_return', method: input.method, staffId: o.staffId })
  }
  o.returnedAt = nowIso()
  o.status = 'returned'
  closeIfSettled(d, orderId)
  for (const item of o.items) {
    const p = d.products.find((x) => x.id === item.productId)
    if (!p || kindOf(d, p) === 'accessory') continue
    p.status = input.productStatus
    if (input.damage > 0 && input.productStatus !== 'available') p.condition = p.condition === 'new' ? 'excellent' : p.condition
  }
}

export function cancelOrder(d: DB, orderId: ID) {
  const o = d.orders.find((x) => x.id === orderId)
  if (!o) return
  o.status = 'cancelled'
  for (const item of o.items) {
    const p = d.products.find((x) => x.id === item.productId)
    if (!p) continue
    if (kindOf(d, p) === 'accessory') {
      if (o.type === 'sale') p.quantity += item.qty
    } else if (p.status === 'reserved') {
      settle(d, p.id)
    }
  }
  for (const a of d.alterations) if (a.orderId === orderId && a.status !== 'delivered') a.status = 'delivered'
}

export function addCharge(d: DB, orderId: ID, c: Omit<Charge, 'id' | 'date'>) {
  const o = d.orders.find((x) => x.id === orderId)
  if (o) o.charges.push({ ...c, id: uid(), date: todayStr() })
}

export function setProductStatus(d: DB, productId: ID, status: Product['status']) {
  const p = d.products.find((x) => x.id === productId)
  if (!p) return
  p.status = status
  if (status === 'available') settle(d, productId)
}

export function saveAlteration(d: DB, a: Alteration) {
  const i = d.alterations.findIndex((x) => x.id === a.id)
  const prev = i >= 0 ? d.alterations[i] : undefined
  if (i >= 0) d.alterations[i] = a
  else d.alterations.unshift(a)
  const p = d.products.find((x) => x.id === a.productId)
  if (!p || p.status === 'sold' || p.status === 'rented') return
  const open = a.status === 'pending' || a.status === 'in_progress' || a.status === 'fitting'
  if (open) p.status = 'alteration'
  else if (p.status === 'alteration') {
    p.status = 'available'
    settle(d, p.id)
  }
  if (prev && prev.productId !== a.productId) settle(d, prev.productId)
}

export function convertLead(d: DB, leadId: ID, clientId: ID) {
  const lead = d.leads.find((l) => l.id === leadId)
  if (!lead || lead.clientId) return
  d.clients.unshift({
    id: clientId, branchId: lead.branchId, name: lead.name, phone: lead.phone, weddingDate: lead.weddingDate,
    lang: 'uz', source: lead.source, measurements: {}, notes: lead.notes, createdAt: nowIso(),
  })
  lead.clientId = clientId
  lead.stage = 'won'
}

export function moveLead(d: DB, leadId: ID, stage: Lead['stage']) {
  const lead = d.leads.find((l) => l.id === leadId)
  if (lead) lead.stage = stage
}

export function logSms(d: DB, entries: Omit<SmsLog, 'id' | 'sentAt'>[]) {
  const at = nowIso()
  for (const e of entries) d.smsLog.unshift({ ...e, id: uid(), sentAt: at })
}

export function deleteAlteration(d: DB, id: ID) {
  const i = d.alterations.findIndex((x) => x.id === id)
  if (i < 0) return
  const [a] = d.alterations.splice(i, 1)
  const p = d.products.find((x) => x.id === a.productId)
  if (p?.status === 'alteration') {
    p.status = 'available'
    settle(d, p.id)
  }
}
