// Business operations. Each takes a mutable draft of the DB (see store.mutate) so related records change together.
import type { Charge, DB, DocFile, ID, Order, Payment, PaymentMethod, Product, SmsLog } from './types'
import { groupByOrder, orderMoney, restingStatus } from './domain'
import { nowIso, todayStr } from '../lib/date'
import { uid } from '../lib/storage'

const kindOf = (d: DB, p: Product) => d.productTypes.find((t) => t.id === p.typeId)?.kind ?? 'dress'

function paymentsOf(d: DB, orderId: ID) {
  return groupByOrder(d.payments).get(orderId) ?? []
}

/** Releases or re-derives a dress's status once nothing specific holds it. */
function settle(d: DB, productId: ID) {
  const p = d.products.find((x) => x.id === productId)
  if (!p || kindOf(d, p) === 'accessory') return
  if (p.status === 'sold' || p.status === 'cleaning') return
  p.status = restingStatus(d, productId)
}

/** `id` is generated by the caller so it can navigate to the new order afterwards. */
export function createOrder(d: DB, id: ID, draft: Omit<Order, 'id' | 'number' | 'createdAt'>, firstPayment?: { amount: number; method: PaymentMethod }): Order {
  const order: Order = { ...draft, id, number: `${d.settings.orderPrefix || 'OR'}-${d.orderSeq}`, createdAt: nowIso() }
  d.orderSeq += 1
  d.orders.push(order)
  for (const item of order.items) {
    const p = d.products.find((x) => x.id === item.productId)
    if (!p) continue
    if (kindOf(d, p) === 'accessory') {
      if (order.type === 'sale') p.quantity = Math.max(0, p.quantity - item.qty)
    } else if (p.status === 'available') {
      p.status = 'reserved'
    }
  }
  if (firstPayment && firstPayment.amount > 0) {
    addPayment(d, { orderId: order.id, branchId: order.branchId, clientId: order.clientId, amount: firstPayment.amount, kind: 'advance', method: firstPayment.method, staffId: order.staffId })
  }
  return order
}

export function addPayment(d: DB, p: Omit<Payment, 'id' | 'date'> & { date?: string }): Payment {
  const payment: Payment = { ...p, id: uid(), date: p.date ?? nowIso() }
  d.payments.unshift(payment)
  if (payment.orderId) closeIfSettled(d, payment.orderId)
  return payment
}

/** A returned rental with nothing left to pay is finished. */
function closeIfSettled(d: DB, orderId: ID) {
  const o = d.orders.find((x) => x.id === orderId)
  if (!o || o.status !== 'returned') return
  if (orderMoney(o, paymentsOf(d, orderId)).balance <= 0) o.status = 'completed'
}

export function handOver(d: DB, orderId: ID, opts: { security?: { amount: number; method: PaymentMethod } }) {
  const o = d.orders.find((x) => x.id === orderId)
  if (!o) return
  o.pickedUpAt = nowIso()
  o.status = o.type === 'sale' ? 'completed' : 'picked_up'
  if (opts.security && opts.security.amount > 0) {
    addPayment(d, { orderId, branchId: o.branchId, clientId: o.clientId, amount: opts.security.amount, kind: 'security', method: opts.security.method, staffId: o.staffId })
  }
  for (const item of o.items) {
    const p = d.products.find((x) => x.id === item.productId)
    if (!p || kindOf(d, p) === 'accessory') continue
    p.status = o.type === 'sale' ? 'sold' : 'rented'
    if (o.type === 'sale') p.quantity = 0
  }
}

export interface ReturnInput {
  lateFee: number
  damage: number
  damageNotes?: string
  refund: number
  method: PaymentMethod
  productStatus: Product['status']
}

export function acceptReturn(d: DB, orderId: ID, input: ReturnInput) {
  const o = d.orders.find((x) => x.id === orderId)
  if (!o) return
  const today = todayStr()
  const held = orderMoney(o, paymentsOf(d, orderId)).securityHeld
  const charge = (kind: Charge['kind'], amount: number, note?: string) => {
    if (amount > 0) o.charges.push({ id: uid(), kind, amount, note, date: today })
  }
  charge('late_fee', input.lateFee)
  charge('damage', input.damage, input.damageNotes)
  if (input.damageNotes) o.damageNotes = input.damageNotes

  // Fees are first kept out of the deposit; whatever the deposit can't cover stays on the balance.
  let fromDeposit = Math.min(held, input.lateFee + input.damage)
  const keep = (amount: number) => {
    const use = Math.min(fromDeposit, amount)
    if (use > 0) addPayment(d, { orderId, branchId: o.branchId, clientId: o.clientId, amount: use, kind: 'fee', method: input.method, fromDeposit: true, staffId: o.staffId })
    fromDeposit -= use
  }
  keep(input.lateFee)
  keep(input.damage)
  if (input.refund > 0) {
    addPayment(d, { orderId, branchId: o.branchId, clientId: o.clientId, amount: input.refund, kind: 'security_return', method: input.method, staffId: o.staffId })
  }
  o.returnedAt = nowIso()
  o.status = 'returned'
  closeIfSettled(d, orderId)
  for (const item of o.items) {
    const p = d.products.find((x) => x.id === item.productId)
    if (!p || kindOf(d, p) === 'accessory') continue
    p.status = input.productStatus
    if (input.damage > 0 && input.productStatus !== 'available') p.condition = p.condition === 'new' ? 'excellent' : p.condition
  }
}

export function cancelOrder(d: DB, orderId: ID) {
  const o = d.orders.find((x) => x.id === orderId)
  if (!o) return
  o.status = 'cancelled'
  for (const item of o.items) {
    const p = d.products.find((x) => x.id === item.productId)
    if (!p) continue
    if (kindOf(d, p) === 'accessory') {
      if (o.type === 'sale') p.quantity += item.qty
    } else if (p.status === 'reserved') {
      settle(d, p.id)
    }
  }
}

export function addCharge(d: DB, orderId: ID, c: Omit<Charge, 'id' | 'date'>) {
  const o = d.orders.find((x) => x.id === orderId)
  if (o) o.charges.push({ ...c, id: uid(), date: todayStr() })
}

export function setProductStatus(d: DB, productId: ID, status: Product['status']) {
  const p = d.products.find((x) => x.id === productId)
  if (!p) return
  p.status = status
  if (status === 'available') settle(d, productId)
}

export function logSms(d: DB, entries: Omit<SmsLog, 'id' | 'sentAt'>[]) {
  const at = nowIso()
  for (const e of entries) d.smsLog.unshift({ ...e, id: uid(), sentAt: at })
}

export function addDocument(d: DB, doc: DocFile) {
  d.documents.unshift(doc)
}

/** Removes the record; the caller deletes the stored file. */
export function removeDocument(d: DB, id: ID) {
  d.documents = d.documents.filter((x) => x.id !== id)
}
